name: tdd_clean_architecture
description: Flutter TDD Clean Architecture

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^2.0.1
  # Bloc for state management
  flutter_bloc: ^4.0.1
  # Value equality
  equatable: ^1.2.0
  # Functional programming thingies
  dartz: ^0.9.1
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+2
  # Local cache
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  bloc_test: ^5.1.0

flutter:
  uses-material-design: true
